---
- hosts: 10.142.0.2
  remote_user: fr970414
  sudo: true
  tasks:
    - name: test connection
      ping:
    - name: psql
        apt:
          name: postgresql 
    - name: postgresql_db
      postgresql_db:
        name: gogs
    - name: postgresql_user
      postgresql_user:
        db: gogs
        name: gogs
        password: 123456
        priv: "CONNECT/gogs:ALL"
    - name: Download foo.conf
      get_url:
        url: https://raw.githubusercontent.com/zhfanrui/CDN/master/ansible.yml
        dest: ~/
